import tkinter
from tkinter import *
from tkinter import messagebox
import pymysql
def insEnq():
    t=tkinter.Tk()
    t.geometry('1450x1250')
    z=Canvas(t,height=1000,width=1500,bg='lightgreen')
    z.place(x=1,y=1)
    z.create_text(800,70,text='   ENQUIRY   ',font="Times 50 bold")
    def clear():
        t.destroy()
    def savedata():
        x=b.get()
        y=d.get()
        z=f.get()
        Q=h.get()
        xx=j.get()
        yy=l.get()
        zz=n.get()
        ss=p.get()
        db=pymysql.connect(host='localhost',user='root',password='root', database="frontOM")
        cur=db.cursor()
        if len(x)==0 or len(y)==0 or len(z)==0 or len(Q)==0 or len(xx)==0 or len(yy)==0 or len(zz)==0 or len(ss)==0 :
        
            messagebox.showerror('ERROR','ENTER ALL FIELDS')
        else:
            s="insert into enquiry values('%s','%s','%s','%s','%s','%s','%s','%s')"%(x,y,z,Q,xx,yy,zz,ss)
            cur.execute(s)
            db.commit()
            messagebox.showinfo('Saved..','Data Saved' )
            db.close()
            b.delete(0,100)
            d.delete(0,100)
            f.delete(0,100)
            h.delete(0,100)
            j.delete(0,100)
            l.delete(0,100)
            n.delete(0,100)
            p.delete(0,100)
            
    a=Label(t,text=' Enquiry-id ',font="Times 25 bold",bd=1,bg="lightgreen" ,fg="black")
    a.place(x=500,y=200)
    b=Entry(t,width=30)
    b.place(x=800,y=200)
    c=Label(t,text=' Student-Name ',font="Times 25 bold",bd=1,bg="lightgreen" ,fg="black")
    c.place(x=500,y=250)
    d=Entry(t,width=30)
    d.place(x=800,y=250)
    e=Label(t,text=' Address ',font="Times 25 bold",bd=1,bg="lightgreen" ,fg="black")
    e.place(x=500,y=300)
    f=Entry(t,width=30)
    f.place(x=800,y=300)
    g=Label(t,text=' City  ',font="Times 25 bold",bd=1,bg="lightgreen" ,fg="black")
    g.place(x=500,y=350)
    h=Entry(t,width=30)
    h.place(x=800,y=350)
    i=Label(t,text=' Phone ',font="Times 25 bold",bd=1,bg="lightgreen" ,fg="black")
    i.place(x=500,y=400)
    j=Entry(t,width=30)
    j.place(x=800,y=400)
    k=Label(t,text=' E-mail ',font="Times 25 bold",bd=1,bg="lightgreen" ,fg="black")
    k.place(x=500,y=450)
    l=Entry(t,width=30)
    l.place(x=800,y=450)
    m=Label(t,text=' Date Of Enquiry ',font="Times 25 bold",bd=1,bg="lightgreen" ,fg="black")
    m.place(x=500,y=500)
    n=Entry(t,width=30)
    n.place(x=800,y=500)
    o=Label(t,text=' Course-id  ',font="Times 25 bold",bd=1,bg="lightgreen" ,fg="black")
    o.place(x=500,y=550)
    p=Entry(t,width=30)
    p.place(x=800,y=550)
    bt=Button(t,text=' Save ',command=savedata,font=" MONOtype 10 bold",bg="green" ,fg="white")
    bt.place(x=800,y=600)
    bt1=Button(t,text=' Back ',command=clear,font=" MONOtype 10 bold",bg="green" ,fg="white")
    bt1.place(x=900,y=600)
    t.mainloop();
#insEnq()    