import tkinter
from tkinter import *
from tkinter import messagebox
import pymysql
def insRes():
    t=tkinter.Tk()
    t.geometry('1450x1250')
    z=Canvas(t,height=1000,width=1500,bg='lightgreen')
    z.place(x=1,y=1)
    z.create_text(800,100,text='   REGISTRATION   ',font="Times 40 bold")
    def cleardata():
        t.destroy()
    def savedata():
        x=b.get()
        y=d.get()
        z=f.get()
        Q=h.get()
        xx=j.get()
        yy=l.get()
        zz=n.get()
        ss=p.get()
        db=pymysql.connect(host='localhost',user='root',password='root', database="frontOM")
        cur=db.cursor()
        if len(x)==0 or len(y)==0  or len(z)==0  or len(Q)==0  or len(xx)==0  or len(yy)==0  or len(zz)==0  or len(ss)==0: 
            messagebox.showerror('ERROR','ENTER ALL FIELDS')
        else:    
            s="insert into Registration values ('%s','%s','%s','%s','%s','%s','%s','%s')"%(x,y,z,Q,xx,yy,zz,ss)
            cur.execute(s)
            db.commit()
            messagebox.showinfo(' Information  ','   Data Saved  ' )
            db.close()
            b.delete(0,100)
            d.delete(0,100) 
            f.delete(0,100)
            h.delete(0,100)
            j.delete(0,100)
            l.delete(0,100)
            n.delete(0,100)
            p.delete(0,100)
           
    a=Label(t,text=' Registration-id ',font="Times 15 bold",bd=5,bg="lightyellow" ,fg="black")
    a.place(x=500,y=180)
    b=Entry(t,width=30)
    b.place(x=800,y=180)
    c=Label(t,text=' Student-Name ',font="Times 15 bold",bd=5,bg="lightyellow" ,fg="black")
    c.place(x=500,y=240)
    d=Entry(t,width=30)
    d.place(x=800,y=240)
    e=Label(t,text=' Address ',font="Times 15 bold",bd=5,bg="lightyellow" ,fg="black")
    e.place(x=500,y=300)
    f=Entry(t,width=30)
    f.place(x=800,y=300)
    g=Label(t,text=' City  ',font="Times 15 bold",bd=5,bg="lightyellow" ,fg="black")
    g.place(x=500,y=360)
    h=Entry(t,width=30)
    h.place(x=800,y=360)
    i=Label(t,text=' Phone ',font="Times 15 bold",bd=5,bg="lightyellow" ,fg="black")
    i.place(x=500,y=420)
    j=Entry(t,width=30)
    j.place(x=800,y=420)
    k=Label(t,text=' E-mail ',font="Times 15 bold",bd=5,bg="lightyellow" ,fg="black")
    k.place(x=500,y=480)
    l=Entry(t,width=30)
    l.place(x=800,y=480)
    m=Label(t,text=' Course-id  ',font="Times 15  bold",bd=5,bg="lightyellow" ,fg="black")
    m.place(x=500,y=540)
    n=Entry(t,width=30)
    n.place(x=800,y=540)
    o=Label(t,text=' Fee-id ',font="Times 15 bold",bd=5,bg="lightyellow" ,fg="black")
    o.place(x=500,y=610)
    p=Entry(t,width=30)
    p.place(x=800,y=610)
    bt=Button(t,text=' Save ',command=savedata,font="Times 10 bold",bg="green" ,fg="white")
    bt.place(x=800,y=660)
    bt=Button(t,text=' Back ',command=cleardata,font="Times 10 bold",bg="green" ,fg="white")
    bt.place(x=900,y=660)
    t.mainloop();
#insRes()    